--- 
- name: Show remote environment 
  shell: env 

- name: Synchronize backend files 
  become: yes
  synchronize: 
    src: ../../backend 
    dest: /home/ubuntu/udapeople-backend 
    recursive: true 

- name: List content 
  become: yes
  shell: |
    echo "Listing content"
    ls /home/ubuntu/udapeople-backend
  register: result 

- name: Print content 
  debug: 
    var: result

- name: Build backend 
  become: yes
  shell: |
    cd /home/ubuntu/udapeople-backend 
    npm install 
    npm run build

- name: Stop any running process 
  shell: |
    pm2 stop default

- name: Start server 
  shell: |
    cd /home/ubuntu/udapeople-backend 
    pm2 start npm -- run "start:prod"
  environment: 
    ENVIRONMENT: production