--- 
- name: Show remote environment 
  shell: env 

- name: Synchronize backend files 
  become: true
  synchronize: 
    src: ../../backend 
    dest: /home/ubuntu/udapeople
    recursive: true 

# - name: List directory content 
#   become: yes
#   shell: |
#     ls /home/ubuntu/udapeople/backend
#   register: result 

# - name: Print directory content 
#   debug: 
#     var: result

- name: Build backend 
  become: true
  shell: |
    cd /home/ubuntu/udapeople/backend
    npm install 
    npm run build

- name: Stop any running process 
  shell: |
    pm2 stop default
  ignore_errors: true

- name: Start server 
  become: true
  shell: |
    cd /home/ubuntu/udapeople/backend 
    pm2 start npm -- run "start:prod"
  environment: 
    ENVIRONMENT: production